export const default_recom = [
  {
    backdrop_path: "/u8QUvrq24pWB2x1DxCy4ulbKJG5.jpg",
    id: 7737,
    title: "Resident Evil 3: Extinción",
    original_title: "Resident Evil: Extinction",
    overview:
      "Tercera entrega de la saga basada en los famosos videojuegos. En esta ocasión, nuestra heroína, Milla Jovovich, junto con los supervivientes de la catástrofe acontecida en la ciudad de Raccoon deben atravesar el desierto de Nevada con la esperanza de llegar a Alaska, antes de que los de la Corporación Umbrella les alcancen.",
    poster_path: "/lP0cconRQqe6O4c6L2mVADDvFyt.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 28, 878],
    popularity: 0.847,
    release_date: "2007-09-20",
    video: false,
    vote_average: 6.302,
    vote_count: 4233,
  },
  {
    backdrop_path: "/fS3ikNlqWtTQhxpRnOQV2E9AdSk.jpg",
    id: 1374,
    title: "Rocky IV",
    original_title: "Rocky IV",
    overview:
      "Nuevas aventuras tanto personales como deportivas del boxeador Rocky Balboa, que en esta ocasión debe enfrentarse a un duro y frío boxeador soviético, llamado Ivan Drago.",
    poster_path: "/2MHUit4H6OK5adcOjnCN6suCKOl.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 3.541,
    release_date: "1985-11-21",
    video: false,
    vote_average: 7.1,
    vote_count: 4488,
  },
  {
    backdrop_path: "/2GFxMsZTiSU7i3GtwRnonx14nrb.jpg",
    id: 983683,
    title: "Bill Burr Presents: Friends Who Kill",
    original_title: "Bill Burr Presents: Friends Who Kill",
    overview:
      "In a night of killer comedy, Bill Burr hosts a showcase of his most raucous stand-up comic pals as they riff on everything from COVID to Michael Jackson.",
    poster_path: "/9gSpgNwjP3Qg8LAsrBgo1Fu6QdL.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35],
    popularity: 2.421,
    release_date: "2022-06-06",
    video: false,
    vote_average: 5.6,
    vote_count: 68,
  },
  {
    backdrop_path: "/ikr0UILfvRerzMNoBTtJtyuWAEV.jpg",
    id: 8078,
    title: "Alien: Resurrección",
    original_title: "Alien Resurrection",
    overview:
      "Más de doscientos años después de su muerte, Ellen Ripley vuelve a la vida gracias al empleo de técnicas avanzadas de clonación. Pero, durante el proceso, el ADN de Ripley se ha mezclado con el de la Reina Alien, por lo que Ripley empieza a desarrollar ciertas características de la peligrosa alienígena.",
    poster_path: "/6MLQ5ehGD3b8E0JZ9K2G4cZeFaI.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [878, 27, 28],
    popularity: 3.868,
    release_date: "1997-11-12",
    video: false,
    vote_average: 6.156,
    vote_count: 5080,
  },
  {
    backdrop_path: "/bOxG9sJ8g9BjX5OVOV9kCR0FDXP.jpg",
    id: 40570,
    title: "Mutiny on the Buses",
    original_title: "Mutiny on the Buses",
    overview:
      "Bus driver Stan Butler agrees to marry Suzy, much to the anguish of Mum, her son-in-law, Arthur, and daughter Olive. How, they wonder, will they ever manage without Stan's money coming in? Then Arthur is sacked, and Stan agrees to delay the wedding. Meanwhile, he hits on an idea: Arthur should learn to drive a bus. Somehow he does just that, and even gets a job. Stan then blackmails the Depot Manager into giving him the job of driver on the new money-making Special Tours Bus. A great idea ...if only the inspector hadn't taken Stan on his trial run to the Windsor Safari Park",
    poster_path: "/4XK9oMfe4Ae53JtXGH45d4c26dG.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35],
    popularity: 1.871,
    release_date: "1972-06-02",
    video: false,
    vote_average: 7.425,
    vote_count: 53,
  },
  {
    backdrop_path: null,
    id: 773804,
    title: "Female Urologists 3",
    original_title: "비뇨기과 여의사들3",
    overview:
      "Haeil, wounded by his wife's words of 'premature ejaculation', goes to a urology department. But because the doctor is a woman, she is so surprised and embarrassed that she tries to go out. Then, a word from a woman doctor catches him. \"How long will you live with premature ejaculation?\". After that, after receiving special treatment, the beautiful female doctor Jeongyeon and glamor nurse Mijoo, Haeil gradually became a man loved by his wife.",
    poster_path: "/tw0ECkTsNJJJHBUqB7f2ybOD2AF.jpg",
    media_type: "movie",
    adult: false,
    original_language: "ko",
    genre_ids: [18, 10749],
    popularity: 0.225,
    release_date: "2020-12-03",
    video: false,
    vote_average: 5.2,
    vote_count: 6,
  },
  {
    backdrop_path: "/1W6zwX287HJU7jVoUQIMpoSnwWi.jpg",
    id: 203912,
    title: "Frankenstein",
    original_title: "National Theatre Live: Frankenstein",
    overview:
      "Infantil en su inocencia pero de forma grotesca, la Criatura desconcertada de Frankenstein es arrojada a un universo hostil por su horrorizado creador. Al encontrarse con la crueldad donde quiera que vaya, la Criatura sin amigos, cada vez más desesperada y vengativa, se determina a rastrear a su creador y hacer un trato aterrador. Preocupaciones urgentes de responsabilidad científica, negligencia de los padres, desarrollo cognitivo y la naturaleza del bien y del mal están incrustados en esta historia emocionante y profundamente inquietante.",
    poster_path: "/vmgxaqnO5N3PlPRAmJ4WMnpuAqb.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 27, 878],
    popularity: 2.755,
    release_date: "2011-03-17",
    video: false,
    vote_average: 8,
    vote_count: 78,
  },
  {
    backdrop_path: "/ne1ivJv3lGGUvZ9F72P0r2xpksB.jpg",
    id: 1375,
    title: "Rocky V",
    original_title: "Rocky V",
    overview:
      "Rocky vuelve de Rusia tras su pelea contra Ivan Drago para encontrarse con que ha perdido casi toda su fortuna. Además, el boxeo le ha dejado ciertas secuelas que fuerzan su retiro. Para lograr salir de la bancarrota Rocky subasta sus cosas y le jura a su hijo que lo va a recuperar todo. Sin más opciones, los Balboa vuelven a su antiguo barrio y a vivir de nuevo en la antigua casa de su mujer con pocos recursos. Un boxeador, llamado Union Cane, gana el título vacante.",
    poster_path: "/tevHaVxtrMTaUi8f3YjLWYSSY8A.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 3.535,
    release_date: "1990-11-16",
    video: false,
    vote_average: 5.8,
    vote_count: 3229,
  },
  {
    backdrop_path: "/7HR38hMBl23lf38MAN63y4pKsHz.jpg",
    id: 666277,
    title: "Vidas pasadas",
    original_title: "Past Lives",
    overview:
      "La familia de Nora emigra a Canadá cuando ella tiene 10 años. Pierde el contacto con su amor de la infancia. Muchos años después, cuando Nora está estudiando teatro en Nueva York, se reencuentra con él online.",
    poster_path: "/jWrJrLMD7SZoxc65KSYej6QOw12.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10749],
    popularity: 3.645,
    release_date: "2023-06-02",
    video: false,
    vote_average: 7.74,
    vote_count: 1849,
  },
  {
    backdrop_path: "/1a1ZpkbE5IkjWnALugYjiU2qij3.jpg",
    id: 282848,
    title: "Doctor Who: El tiempo del Doctor",
    original_title: "Doctor Who: The Time of the Doctor",
    overview:
      "Orbitando un pequeño y pacífico planeta, los ejércitos de las especies más letales del universo se reúnen, atraídas por un misterioso mensaje que se repite por las estrellas. Y entre ellos, está el Doctor. Rescatando a Clara de una cena navideña en familia, el Señor del Tiempo y su mejor amiga descubren lo que esta enigmática señal significa para su propio destino y para el resto del universo.",
    poster_path: "/cS0WmE5Hpq1HyLlpuAJ6SoHR2aS.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18, 878, 10770],
    popularity: 3.533,
    release_date: "2013-12-25",
    video: false,
    vote_average: 8.1,
    vote_count: 296,
  },
  {
    backdrop_path: "/6kqybERm5qi2jGpu8I7DaQPxpSU.jpg",
    id: 2011,
    title: "Persépolis",
    original_title: "Persepolis",
    overview:
      "Marjane Satrapi (Gabrielle Lopes) es una niña iraní de 8 años que sueña con ser profeta para salvar el mundo. Querida por sus padres y adorada por su abuela, Marjane sigue atenta los acontecimientos que provocan la caída del Shah y de su régimen brutal para dejar paso a una República Islámica que controla la manera de vestir y de actuar de la gente. Ésto provoca que Marjane se vea obligada a llevar velo, lo que la anima a convertirse en una revolucionaria.",
    poster_path: "/1XSTjORhsqSQgdYTzHrAuPDVC2.jpg",
    media_type: "movie",
    adult: false,
    original_language: "fr",
    genre_ids: [16, 18],
    popularity: 3.783,
    release_date: "2007-06-27",
    video: false,
    vote_average: 7.895,
    vote_count: 1979,
  },
  {
    backdrop_path: "/hCxxOJojCUFyuahDx167glJgp7E.jpg",
    id: 1368,
    title: "Acorralado",
    original_title: "First Blood",
    overview:
      "John Rambo es un veterano de la guerra de Vietnam que sufre de estrés postraumático. Un día, llega a un pequeño pueblo de Oregón, donde el sheriff Will Teasle le detiene por vagabundear. Rambo logra escapar de la comisaría y se refugia en el bosque, donde usa sus habilidades de supervivencia y combate para enfrentarse a los policías que le persiguen. El coronel Samuel Trautman, el antiguo jefe de Rambo, llega al pueblo para intentar negociar con él y evitar una masacre. Rambo tendrá que luchar contra sus propios demonios y contra las fuerzas del orden que le quieren capturar o matar.",
    poster_path: "/sYHRcd9p3rV3t3w8MHGaA7wdIBl.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 53, 10752],
    popularity: 4.116,
    release_date: "1982-10-22",
    video: false,
    vote_average: 7.484,
    vote_count: 6387,
  },
  {
    backdrop_path: "/vfEORWH75d5qSHe3QBkSPIsXhOz.jpg",
    id: 11712,
    title: "Sanjuro",
    original_title: "椿三十郎",
    overview:
      "En el Japón de la era Tokugawa, un grupo de nueve jóvenes samuráis está decidido a acabar con la corrupción reinante y a acabar con todos los que están relacionados con ella. Consiguen el apoyo del inspector de policía Kikui y se preparan para llevar a cabo su plan. Poco después, aparece Sajuro, un personaje salido de entre las sombras, que empezará a actuar y a poner orden en medio del caos.",
    poster_path: "/v45YU8EQe0zgRI0nYwQ0NcBUEjg.jpg",
    media_type: "movie",
    adult: false,
    original_language: "ja",
    genre_ids: [18, 28, 35],
    popularity: 3.781,
    release_date: "1962-01-01",
    video: false,
    vote_average: 7.9,
    vote_count: 628,
  },
  {
    backdrop_path: null,
    id: 775293,
    title: "Matrix",
    original_title: "Matrix",
    overview:
      '"MATRIX is a flicker film which utilizes 81 still photographs of my wife\'s head. It is a film dependent upon variation of intense light changes by calculated combinations of black and white frame alternations with exposure changes. Throughout, the light intensity rises and falls as the head rotates in varying directions within a 360 degree frontal area." — James Cagle',
    poster_path: "/frDqG8rmqKUg4HzQ604LZo8VLHB.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [],
    popularity: 0.882,
    release_date: "1973-01-01",
    video: false,
    vote_average: 6.8,
    vote_count: 25,
  },
  {
    backdrop_path: null,
    id: 51021,
    title: "A Lure: Teen Fight Club",
    original_title: "A Lure: Teen Fight Club",
    overview:
      "Tres estudiantes de Belmont mixto Highschool desaparecen sin dejar rastro de su paradero. La presión está en la policía para capturar a los culpables. La detective Maggie Rawdon entra en Belmont High como estudiante de intercambio en un intento por resolver la desaparición  de los estudiantes.",
    poster_path: "/ipl6NdM0LwyakzLH9gKBDn8YhmZ.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 18, 80],
    popularity: 0.849,
    release_date: "2010-11-16",
    video: false,
    vote_average: 7.1,
    vote_count: 24,
  },
  {
    backdrop_path: "/sPZsYoBK92pOSMPTaXJ5DeIMgq.jpg",
    id: 339,
    title: "Noche en la tierra",
    original_title: "Night on Earth",
    overview:
      "Película dividida en historias independientes a través de las cuales Jim Jarmusch presenta el panorama nocturno de cinco grandes ciudades (Los Angeles, Nueva York, París, Roma y Helsinki), con un taxi, y lo que en él ocurre desde el anochecer hasta el amanecer de un mismo día, y obviamente con diferentes personajes, como hilo conductor.",
    poster_path: "/dNA14GVmnU2r7isrojCTwzXP9ig.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [35, 18],
    popularity: 3.611,
    release_date: "1991-12-12",
    video: false,
    vote_average: 7.5,
    vote_count: 936,
  },
  {
    backdrop_path: "/tY36rkGlREg5m9CaguckR8jZCye.jpg",
    id: 653851,
    title: "Devotion. Una historia de héroes",
    original_title: "Devotion",
    overview:
      "Basada en hechos reales. En 1950, cuando la Guerra Fría amenaza la paz internacional, dos jóvenes pilotos de diferentes mundos son aceptados en un escuadrón de élite para su entrenamiento: uno es Tom Hudner, un soldado impecable. El otro es Jesse Brown, un talentoso piloto, que se convertiría en el primer afroamericano en volar en combate para la Marina de los Estados Unidos. Iniciados juntos en el escuadrón VF-32, Tom y Jesse son llevados al límite para convertirse en los mejores pilotos de combate. donde formarán una firme amistad.",
    poster_path: "/dBYfbtWzmeKhQnlXdEzaPKwX9ii.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [10752, 18, 28],
    popularity: 3.843,
    release_date: "2022-11-23",
    video: false,
    vote_average: 7.1,
    vote_count: 728,
  },
  {
    backdrop_path: "/puiwodUrPSDTkvlIRr2CdDM1isB.jpg",
    id: 26342,
    title: "The Terminators",
    original_title: "The Terminators",
    overview:
      "A small band of resistance fighters battle the cyborgs that have taken control of the planet.",
    poster_path: "/7LV3sg3bJOGFD6J0gn7Wt1IL5SK.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 27, 878],
    popularity: 2.614,
    release_date: "2009-04-28",
    video: false,
    vote_average: 4.1,
    vote_count: 74,
  },
  {
    backdrop_path: "/pKgfWzxOpvGV3MQ0kLjLdjKAzUe.jpg",
    id: 785538,
    title: "7 prisioneros",
    original_title: "7 Prisioneiros",
    overview:
      "Para ofrecer una vida mejor a su familia en el país, Mateus, de 18 años, acepta un trabajo en un vertedero de São Paulo para su nuevo jefe, Luca, pero se ve atrapado en el peligroso mundo del tráfico de personas.",
    poster_path: "/zLOf5qU2vx3cYRGkm5PDJBHxEq4.jpg",
    media_type: "movie",
    adult: false,
    original_language: "pt",
    genre_ids: [18, 80],
    popularity: 3.547,
    release_date: "2021-10-22",
    video: false,
    vote_average: 7.047,
    vote_count: 351,
  },
  {
    backdrop_path: "/edH2sKM63YiSEOWoaJPN87a71dZ.jpg",
    id: 777245,
    title: "Ellas hablan",
    original_title: "Women Talking",
    overview:
      "Un grupo de mujeres en una colonia religiosa aislada lucha por reconciliar su fe con una serie de agresiones sexuales cometidas por los hombres de la colonia.",
    poster_path: "/ic1LmfuGibGJMYjdz1Pobxeouon.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 3.813,
    release_date: "2022-12-23",
    video: false,
    vote_average: 6.9,
    vote_count: 610,
  },
]

export const default_hero = {
  adult: false,
  backdrop_path: null,
  budget: 0,
  genres: [
    {
      id: 99,
      name: "Documental",
    },
  ],
  homepage: "",
  id: 1434009,
  imdb_id: "tt35301026",
  origin_country: ["KZ"],
  original_language: "kk",
  original_title: "We Live Here",
  overview: "",
  popularity: 22.446,
  poster_path: "/uXhG2CGyP2hIUXoD7Yh0sl5uXft.jpg",
  production_companies: [],
  production_countries: [
    {
      iso_3166_1: "KZ",
      name: "Kazakhstan",
    },
  ],
  release_date: "2025-03-19",
  revenue: 0,
  runtime: 0,
  spoken_languages: [
    {
      iso_639_1: "kk",
      name: "қазақ",
    },
  ],
  status: "Released",
  tagline: "",
  title: "We Live Here",
  video: false,
  vote_average: 0,
  vote_count: 0,
}
